#!/usr/bin/env python3
"""
Convert G1 29DOF motion CSV to G1 23DOF CSV in Isaac Lab joint order.

This script is essential for C++ deployment compatibility:
- Isaac Lab training uses NPZ files with proper joint remapping
- C++ deployment reads CSV directly without remapping
- Therefore CSV must be in Isaac Lab order for deployment to work correctly

Input:  29DOF CSV (36 columns: 7 pose + 29 joints in SDK order)
Output: 23DOF CSV (30 columns: 7 pose + 23 joints in Isaac Lab order)

Usage:
    python convert_29dof_to_23dof_isaac_order.py --input path/to/29dof.csv --output path/to/23dof.csv

    # Or convert all dance motions:
    python convert_29dof_to_23dof_isaac_order.py --all
"""

import argparse
import numpy as np
import os
from pathlib import Path

# joint_ids_map for G1-23DOF: Isaac Lab joint index -> SDK motor index
# This comes from deploy.yaml which is generated by export_deploy_cfg.py
# based on joint_sdk_names with empty placeholders for non-existent joints
JOINT_IDS_MAP_23DOF = [
    0, 6, 12,      # left_hip_pitch, right_hip_pitch, waist_yaw
    1, 7,          # left_hip_roll, right_hip_roll
    15, 22,        # left_shoulder_pitch, right_shoulder_pitch
    2, 8,          # left_hip_yaw, right_hip_yaw
    16, 23,        # left_shoulder_roll, right_shoulder_roll
    3, 9,          # left_knee, right_knee
    17, 24,        # left_shoulder_yaw, right_shoulder_yaw
    4, 10,         # left_ankle_pitch, right_ankle_pitch
    18, 25,        # left_elbow, right_elbow
    5, 11,         # left_ankle_roll, right_ankle_roll
    19, 26,        # left_wrist_roll, right_wrist_roll
]

# SDK joint names for reference
SDK_JOINT_NAMES = [
    "left_hip_pitch_joint",       # SDK 0
    "left_hip_roll_joint",        # SDK 1
    "left_hip_yaw_joint",         # SDK 2
    "left_knee_joint",            # SDK 3
    "left_ankle_pitch_joint",     # SDK 4
    "left_ankle_roll_joint",      # SDK 5
    "right_hip_pitch_joint",      # SDK 6
    "right_hip_roll_joint",       # SDK 7
    "right_hip_yaw_joint",        # SDK 8
    "right_knee_joint",           # SDK 9
    "right_ankle_pitch_joint",    # SDK 10
    "right_ankle_roll_joint",     # SDK 11
    "waist_yaw_joint",            # SDK 12
    "waist_roll_joint",           # SDK 13 - NOT IN 23DOF
    "waist_pitch_joint",          # SDK 14 - NOT IN 23DOF
    "left_shoulder_pitch_joint",  # SDK 15
    "left_shoulder_roll_joint",   # SDK 16
    "left_shoulder_yaw_joint",    # SDK 17
    "left_elbow_joint",           # SDK 18
    "left_wrist_roll_joint",      # SDK 19
    "left_wrist_pitch_joint",     # SDK 20 - NOT IN 23DOF
    "left_wrist_yaw_joint",       # SDK 21 - NOT IN 23DOF
    "right_shoulder_pitch_joint", # SDK 22
    "right_shoulder_roll_joint",  # SDK 23
    "right_shoulder_yaw_joint",   # SDK 24
    "right_elbow_joint",          # SDK 25
    "right_wrist_roll_joint",     # SDK 26
    "right_wrist_pitch_joint",    # SDK 27 - NOT IN 23DOF
    "right_wrist_yaw_joint",      # SDK 28 - NOT IN 23DOF
]


def convert_29dof_to_23dof_isaac_order(input_csv: str, output_csv: str, verbose: bool = True) -> np.ndarray:
    """
    Convert 29DOF CSV (SDK order) to 23DOF CSV (Isaac Lab order).

    Args:
        input_csv: Path to input 29DOF CSV file
        output_csv: Path to output 23DOF CSV file
        verbose: Print progress information

    Returns:
        Converted data array
    """
    # Load 29DOF CSV
    data_29dof = np.loadtxt(input_csv, delimiter=',')

    if verbose:
        print(f"Input: {input_csv}")
        print(f"  Shape: {data_29dof.shape} (expected: N x 36)")

    if data_29dof.shape[1] != 36:
        raise ValueError(f"Expected 36 columns (7 pose + 29 joints), got {data_29dof.shape[1]}")

    num_frames = data_29dof.shape[0]

    # Extract pose (columns 0-6: x, y, z, qx, qy, qz, qw)
    pose = data_29dof[:, :7]

    # Extract joints in SDK order (columns 7-35: SDK joints 0-28)
    joints_sdk_order = data_29dof[:, 7:]

    # Remap to Isaac Lab order for 23DOF
    # Isaac Lab joint i should contain data from SDK joint JOINT_IDS_MAP_23DOF[i]
    joints_isaac_order = np.zeros((num_frames, 23), dtype=np.float64)

    if verbose:
        print("\nJoint remapping (Isaac Lab -> SDK):")

    for isaac_idx, sdk_idx in enumerate(JOINT_IDS_MAP_23DOF):
        joints_isaac_order[:, isaac_idx] = joints_sdk_order[:, sdk_idx]
        if verbose and isaac_idx < 5:  # Print first 5 for verification
            print(f"  Isaac Lab [{isaac_idx:2d}] <- SDK [{sdk_idx:2d}] ({SDK_JOINT_NAMES[sdk_idx]})")

    if verbose:
        print(f"  ... ({len(JOINT_IDS_MAP_23DOF) - 5} more joints)")

    # Combine pose + joints
    data_23dof = np.hstack([pose, joints_isaac_order])

    if verbose:
        print(f"\nOutput: {output_csv}")
        print(f"  Shape: {data_23dof.shape} (expected: N x 30)")

    # Save
    os.makedirs(os.path.dirname(output_csv) if os.path.dirname(output_csv) else '.', exist_ok=True)
    np.savetxt(output_csv, data_23dof, delimiter=',', fmt='%.6f')

    if verbose:
        print(f"  Saved successfully!")

    return data_23dof


def convert_all_motions():
    """Convert all known motion files from 29DOF to 23DOF."""

    base_dir = Path(__file__).parent.parent.parent  # unitree_rl_lab root

    # Motion files to convert
    motions = [
        {
            "name": "bata_dias",
            "input": base_dir / "deploy/robots/g1_29dof/config/policy/mimic/bata_dias/params/bata_dias_full_60hz.csv",
            "output": base_dir / "deploy/robots/g1_23dof/config/policy/mimic/bata_dias/params/bata_dias_23dof_60hz.csv",
        },
        {
            "name": "gangnam_style",
            "input": base_dir / "source/unitree_rl_lab/unitree_rl_lab/tasks/mimic/robots/g1_29dof/gangnanm_style/G1_gangnam_style_V01.bvh_60hz.csv",
            "output": base_dir / "deploy/robots/g1_23dof/config/policy/mimic/gangnam_style/params/gangnam_style_23dof_60hz.csv",
        },
        {
            "name": "dance_102",
            "input": base_dir / "source/unitree_rl_lab/unitree_rl_lab/tasks/mimic/robots/g1_29dof/dance_102/G1_Take_102.bvh_60hz.csv",
            "output": base_dir / "deploy/robots/g1_23dof/config/policy/mimic/dance_102/params/dance_102_23dof_60hz.csv",
        },
    ]

    print("=" * 60)
    print("Converting all motion files from 29DOF to 23DOF (Isaac Lab order)")
    print("=" * 60)

    for motion in motions:
        print(f"\n{'='*60}")
        print(f"Converting: {motion['name']}")
        print(f"{'='*60}")

        if not motion["input"].exists():
            print(f"  WARNING: Input file not found: {motion['input']}")
            continue

        try:
            convert_29dof_to_23dof_isaac_order(
                str(motion["input"]),
                str(motion["output"]),
                verbose=True
            )
        except Exception as e:
            print(f"  ERROR: {e}")

    print(f"\n{'='*60}")
    print("Done!")
    print("="*60)


def main():
    parser = argparse.ArgumentParser(
        description="Convert G1 29DOF motion CSV to 23DOF in Isaac Lab order"
    )
    parser.add_argument(
        "--input", "-i",
        type=str,
        help="Path to input 29DOF CSV file"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="Path to output 23DOF CSV file"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Convert all known motion files (bata_dias, gangnam_style, dance_102)"
    )

    args = parser.parse_args()

    if args.all:
        convert_all_motions()
    elif args.input and args.output:
        convert_29dof_to_23dof_isaac_order(args.input, args.output)
    else:
        parser.print_help()
        print("\nError: Either --all or both --input and --output are required")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
